Net:
  output_channels: 2
  enc_type: 'xception65'
  dec_type: 'aspp'
  output_stride: 8
Data:
  dataset: 'sherbrooke'
  target_size: (544,544)
Train:
  max_epoch: 2400
  batch_size: 8
  fp16: False
  resume: False
  pretrained_path: '../model/cityscapes_2cl_deeplab_v3_plus/model.pth'
  freeze_to_layer: 'logits'   
  freeze_bn: False
Loss:
  loss_type: 'Lovasz'
  ignore_index: 255
Optimizer:
  mode: 'sgd'
  base_lr: 0.0007
  t_max: 30