Net:
  output_channels: 2
  enc_type: 'efficientnet-b4'
  dec_type: 'unet'
  pretrained: True
Data:
  dataset: 'sherbrooke'
  target_size: (768, 768)
Train:
  max_epoch: 2400
  batch_size: 8
  fp16: False
  resume: False
  pretrained_path:
Loss:
  loss_type: 'Lovasz'
  ignore_index: 255
Optimizer:
  mode: 'adabound'
  base_lr: 0.007
  t_max: 30
