Net:
  output_channels: 2
  enc_type: 'mobilenetv2'
  dec_type: 'maspp'
  output_stride: 8
  pretrained: False
Data:
  dataset: 'sherbrooke'
  target_size: (768,768)
  defects: False
Train:
  max_epoch: 2400
  batch_size: 32
  fp16: False
  resume: False
  pretrained_path: '../model/sherbrooke_deeplabv3p_lgpu_mnv2_300-2/model.pth'
  freeze_to_layer: False   
  freeze_bn: False
Loss:
  loss_type: 'Lovasz'
  ignore_index: 255
Optimizer:
  mode: 'adabound'
  base_lr: 0.0007
  t_max: 30